### ISSUE TITLE
fix memory leak in test_gmic_image_to_numpy_array_fuzzying

### ISSUE THREAD

**Issue by myselfhimself** [myselfhimself/gmic-py#61]
- [x] fix leak
- [x] fix test_gmic_image_parameters_fuzzying pytest case segfault
- [x] use `tp_new` instead of `tp_init` for `GmicImage`, + `tp_alloc`, `tp_dealloc`, `tp_free`
- [x] use `tp_new` instead of `tp_init` for `Gmic`, + `tp_alloc`, `tp_dealloc`, `tp_free`
- [x] GmicImage: write psutil-based pytest with instancing, deleting of GmicImage and used memory delta observation
- [x] make test suite green again
- [x] Gmic: write psutil-based memory test

+200MB every 10 tests or so

`GmicImage.to_numpy_array()` suspected to leak

topmost python process has an evergrowing memory footprint when the parametrized `test_gmic_image_to_numpy_array_fuzzying` test is run, see screenshots below:

**Before**
![beforeMemoryLeak](https://user-images.githubusercontent.com/1265346/92303521-e62ad400-ef75-11ea-9f70-81062af534ee.png)

**After**
![afterMemoryLeak](https://user-images.githubusercontent.com/1265346/92303518-e1feb680-ef75-11ea-9c51-455300ca5e22.png)

Related to #48

**Comment by myselfhimself** [comment]
Investigating...

There are three memory freeing issues :
- `GmicImage.tp_dealloc` is not called on del but just on `del the_gmic_image`; using Python >= 3.4 safer [`tp_finalize` method defined by PEP 442](https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_finalize) might help solved this

[Per the PEP 442's benefits:
](https://www.python.org/dev/peps/pep-0442/#id4)
```
The PEP also paves the way for further benefits:

    The module shutdown procedure may not need to set global variables to None anymore. This could solve a well-known class of irritating issues.

```
- `GmicImage.tp_dealloc` does not free the `PyGmicImage.gmic_image` attribute object. It is unclear how to do it, because it is a `gmic_image` itself, not a `gmic_image*`.

- `GmicImage.to_numpy_array`'s returned numpy arrays' buffers do not get freed once the python parametrized test case ends, possibly due to numpy preserving the foreign 'buffer'-injected parameter's data even on python numpy array destruction, similarly to the gmic_image 'shared' mechanism. Or maybe because the whole test function is run in a try-catch by `pytest`

**Comment by myselfhimself** [comment]
Using the [memory_profiler](http://pypi.python.org/pypi/memory_profiler) [psutil](https://pypi.org/project/psutil/)-based module...
- `gmic.GmicImage()` allocates data in silence and possibly does not free it, or frees it in silence.
- numpy on the contrary allocates data publicly for `psutil` and it frees data on a simple `variable = None` or `del variable` 

```
Line #    Mem usage    Increment   Line Contents
================================================
     7     16.5 MiB     16.5 MiB   @profile
     8                             def my_func():
     9     30.4 MiB     13.8 MiB       import numpy
    10     35.7 MiB      5.4 MiB       z = numpy.full((10,100,438,3), 3.5, numpy.float32)
    11     35.7 MiB      0.0 MiB       print("z", type(z), z.flags, z.__array_interface__, rf(z))
    12     30.8 MiB      0.0 MiB       z = None
    13     88.7 MiB     57.9 MiB       import gmic
    14     88.7 MiB      0.0 MiB       a = gmic.GmicImage(struct.pack(*('1024f',) + tuple([random.random() for a in range(1024)])), 32, 32)
    15     88.7 MiB      0.0 MiB       print(rf(a))
    16     88.7 MiB      0.0 MiB       a = None
    17     88.7 MiB      0.0 MiB       print(rf(a))

```

I need to look more into numpy's C code (`multiarray` type, which is the underlying name of the Python `numpy.ndarray` name)..

**Comment by myselfhimself** [comment]
Memory freeing for gmic.GmicImage does happen.. within gdb-run numpy's test suite tool ! (But with the regular python 3.7.5 executable...)

```
(numpybuild37) jd@jd-ThinkPad-T400:~/Productions/GMIC/numpy$ gdb --args python runtests.py -g --python ../test_memory_freeing.py 
GNU gdb (Ubuntu 8.3-0ubuntu1) 8.3
...
(Pdb) c
/////// Numpy array allocation and freeing
pfullmem(rss=90972160, vms=332398592, shared=59682816, text=2596864, lib=0, data=53702656, dirty=0, uss=68653056, pss=71090176, swap=0)
1.1083018220601288 # percentage of process memory
pfullmem(rss=811175936, vms=1052614656, shared=59682816, text=2596864, lib=0, data=773918720, dirty=0, uss=788946944, pss=791384064, swap=0)
9.846781872378722  # percentage of process memory
2
pfullmem(rss=91156480, vms=332451840, shared=59682816, text=2596864, lib=0, data=53755904, dirty=0, uss=68800512, pss=71237632, swap=0)
1.106561554506423  # percentage of process memory
----------------------
// GmicImage allocation and tentative freeing
pfullmem(rss=91156480, vms=332451840, shared=59682816, text=2596864, lib=0, data=53755904, dirty=0, uss=68800512, pss=71237632, swap=0)
1.106561554506423  # percentage of process memory
pfullmem(rss=811159552, vms=1052454912, shared=59682816, text=2596864, lib=0, data=773758976, dirty=0, uss=788803584, pss=791240704, swap=0)
9.846781872378722  # percentage of process memory
pfullmem(rss=91156480, vms=332451840, shared=59682816, text=2596864, lib=0, data=53755904, dirty=0, uss=68800512, pss=71237632, swap=0)
1.106561554506423  # percentage of process memory
sleep # 3 seconds sleep
pfullmem(rss=91156480, vms=332451840, shared=59682816, text=2596864, lib=0, data=53755904, dirty=0, uss=68800512, pss=71237632, swap=0)
1.106561554506423  # percentage of process memory
````

test_memory_freeing.py` script:
```python
import numpy
import sys
import psutil
import gmic
import struct
import pdb; pdb.set_trace()
import time

p = psutil.Process()
print(p.memory_full_info())
print(p.memory_percent())
a = numpy.full((400,500,300,3), 4.5, numpy.float32)
print(p.memory_full_info())
print(p.memory_percent())
print(sys.getrefcount(a))

del a
print(p.memory_full_info())
print(p.memory_percent())

print("----------------------")

print(p.memory_full_info())
print(p.memory_percent())
a = gmic.GmicImage(struct.pack(*(('180000000f',) + (4.5,)*180000000)), 400,500,300,3)
print(p.memory_full_info())
print(p.memory_percent())
del a
print(p.memory_full_info())
print(p.memory_percent())

time.sleep(3)
print("sleep")
print(p.memory_full_info())
print(p.memory_percent())
```

**Comment by myselfhimself** [comment]
OK enough searching...
numpy's run_tests.py executes test script through Python's native exec() script string evaluation function.. Using it as well and printing gmic.__spec__ highlighted that I had been loading an old forgotten gmic-py .so file, never impacted by recompilations, located in the same directory as the script itself...

**Comment by myselfhimself** [comment]
related parse_gui / gmic_stdlib parse_gui fix: https://github.com/dtschump/gmic/issues/256

**Comment by myselfhimself** [comment]
pretty much OK, letting the MacOS tests flaky (strange segfaults) and closing this

**Comment by eyaler** [comment]
i stumbled upon what seems like memory leaking with conversions from numpy and back. are there guidelines for best practices for clearing memory?
i have something like:
```
gim = gmic.GmicImage.from_numpy_helper(im, deinterleave=True)
gims = [gim]
gmic.run(filters, gims)
npim = gims[0].to_numpy_helper(interleave=True, permute='yxzc', squeeze_shape=True)
ret = np.uint8(npim*255)  
```
i tried deleting different object but no luck

**Comment by myselfhimself** [comment]
Hello @eyaler,
Thank you for reporting this.
Could you please show gmic.__version__ and other gmic.__* objects ? What is
your operating system, is it 32 bits or 64bits?
Which object type precisely have you deleted? A GmicImage, a Python list
with GmicImage objects inside, or a numpy array?
Some leak tests have indeed been made, but then removed from the unit test
suites. Also those tests were very flaky, in that object freeing in Python
is difficult to control, especially for someone not very experienced in
Python bindings like me.
It may be time to retry to trace down those leaks and fix them, especially
if your business application is memory intensive or repeats a lot.
I am happy to see someone using so many to_numpy_helper() parameters (it
took me time to implement them..).
Thanks in advance

po 5. 7. 2021 v 10:12 odesílatel eyaler ***@***.***> napsal:

**Comment by eyaler** [comment]
hi, i deleted my comment since i later found my solution in the tutorial.rst (i was recreating the runtime over and over)

**Comment by myselfhimself** [comment]
Very good, yes, you would have several runtime handles hanging otherwise.
Having just one spares you from consecutive spawning durations and from
apparent memory leaks which are not.
You may try to delete your gmic.Gmic object in the end with Python's "del"
keyword, but it is unsure that the c++ runtime object will be freed.

The release of various Linux (or Windows) builds has been put on hold,
because of my personal schedule. I would like to retackle a building and
releasing pipeline for both OSes, following G'MIC official versioning
closer, this summer maybe. Feel free to share your need for this; as a kind
of motivation for me for fresher package management.


po 5. 7. 2021 v 17:00 odesílatel eyaler ***@***.***> napsal:

**Comment by eyaler** [comment]
@myselfhimself hi. so upon further investigation my issue is with `from_numpy` causing a memory spike after several 100-1000 of iterations depending on image size. here is a minimal notebook to recreate:
https://colab.research.google.com/drive/1POar0xO9cPUYFdhUHzxAgtNuC_veaGo7
when using the file system to load a file directly in gmic it does not crash.
in the mean time it would be great to have python code to replace this function.

**Comment by eyaler** [comment]
i added to the notebook also crash example with `to_numpy`. and just to mention i hit these issues initially on 2.9.2 but also get them on 2.9.4a1

**Comment by myselfhimself** [comment]
@eyaler
Hello thank you for having unlocked the access to your Google Colab, let me
look at this on this week-end.
Yes, it is possible to give a Python implementation... I will try to find
one this week-end. When developing gmic-py I used to write first the
algorithm in Python, then develop the algorithm bits in CPython little by
little.
I did not have in mind a use of case where gmic is used for many
iterations. Thanks for uncovering those memory issues.

út 5. 10. 2021 v 3:29 odesílatel eyaler ***@***.***> napsal:

**Comment by eyaler** [comment]
thanks. i am using it as part of a video manipulation pipeline here. [j.mp/vid2green](https://j.mp/vid2green), and doing it frame by frame for many frames.

**Comment by myselfhimself** [comment]
Hello a gmic-py fork for fixing memory leaks has been made in the same lab which created G'MIC.
See https://github.com/GreycLab/gmic-py

**Comment by eyaler** [comment]
> Hello a gmic-py fork for fixing memory leaks has been made in the same lab which created G'MIC. See https://github.com/GreycLab/gmic-py

@myselfhimself 
Thanks!

does it also address any other of the issues?
is there a notebook showing how to install it?
