### ISSUE TITLE
Extract style checker from build jobs

### ISSUE THREAD

**Issue by myselfhimself** [myselfhimself/gmic-py#76]
Pointed out by @Czaki on https://github.com/joerick/cibuildwheel/issues/329

**Comment by Czaki** [comment]
Github actions allow adding dependency between steps 
see https://github.com/4DNucleome/PartSeg/blob/master/.github/workflows/tests.yml

So you could add a check in the first step, and then if this check fail no build step is executed.

**Comment by myselfhimself** [comment]
@Czaki thank you.. I confused jobs and steps for isolating this code style part. Unfortunately Github Action does not allow for sub-workflow mutualisation
